
mju-sed.exe: mju-sed.cpp
  cl /nologo /EHsc /Ox /Gy /GL  mju-sed.cpp

lemon.exe: lemon.c
  cl /nologo /EHsc /Ox /Gy /GL  lemon.c


clean:
  -del mju-sed.exe
  -del mju-sed.obj
  -del lemon.exe
  -del lemon.obj